<a href="https://colab.research.google.com/github/Saadkhan55/Arm-Intern-Challenge/blob/master/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from random import gauss
from scipy import constants

In [0]:
# Generates a random univt vector using gauss
# then divides by magnitude to make it unit
def rand_vector(length):
    unit_vector = [gauss(0, 1) for i in range(length)]
    size = sum(x**2 for x in unit_vector) ** 0.5
    return [x/size for x in unit_vector]
    
def grad_approx(cost, x):
  grad = x.copy()
  for i in range(len(x)):
    xi1 = x.copy()
    xi2 = x.copy()
    xi1[i] = xi1[i] + 0.01
    xi2[i] = xi2[i] - 0.01
    grad[i] = ((cost(xi1) - cost(xi2))/0.02)
  return grad

In [0]:
def gradient_descent_step(x, cost, grad=None, step_size="backtracking"):
  if(grad == "random"):
    grad2 = np.array(rand_vector(len(x)))
  elif (hasattr(grad, '__call__')):
    grad2 = np.array(grad(x))
  else:
    grad2 = grad_approx(cost, x)
  if(( isinstance(step_size, int)) or (isinstance(step_size, float))):
    step=step_size
  elif(step_size=="backtracking"):
    step=1
    while( (cost(x)-cost(x-step*grad2)) < ((step*np.linalg.norm(grad2)**2)/3) ):
      step = step*0.3
  elif(step_size == "line_search"):
    line = [-1, 1]
    while((line[1]- line[0])>0.001):
      if(f(np.array(line[0]))<f(np.array(line[1]))):
        line[1]-=(constants.golden*(line[1]-line[0]) - (line[1]-line[0]))
      else:
        line[0]+=(constants.golden*(line[1]-line[0]) - (line[1]-line[0]))
    step = (((line[1]-line[0])/2)+line[0])
  return (x - (grad2)*step)

In [0]:
def gradient_descent(initial_x, cost, num_steps, grad=None, step_size="backtracking"):
# Your code goes here
  x = initial_x
  trace = []
  trace.append(x)
  for i in range(1, num_steps):
    x = gradient_descent_step(trace[i-1], cost, grad, step_size)
    trace.append(x)
  return x, trace

In [291]:
# For testing purposes
cost = lambda x: np.sum(x**2)
grad = lambda x: 2*x
x = np.array([12,11, 32, 21, 16])
steps = "backtracking"
gradient_descent(initial_x=x,cost=f, grad = grad, num_steps = 5,  step_size ="line_search")

(array([0.92530459, 0.84819588, 2.46747892, 1.61928304, 1.23373946]),
 [array([12, 11, 32, 21, 16]),
  array([ 6.32349405,  5.79653621, 16.86265079, 11.06611458,  8.4313254 ]),
  array([3.33221475, 3.05453019, 8.88590599, 5.83137581, 4.442953  ]),
  array([1.75593668, 1.60960862, 4.6824978 , 3.07288918, 2.3412489 ]),
  array([0.92530459, 0.84819588, 2.46747892, 1.61928304, 1.23373946])])