<a href="https://colab.research.google.com/github/Saadkhan55/Arm-Intern-Challenge/blob/master/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from random import gauss
from scipy import constants
%matplotlib inline

In [0]:
def make_rand_vector(dims):
    vec = [gauss(0, 1) for i in range(dims)]
    mag = sum(x**2 for x in vec) ** .5
    return [x/mag for x in vec]

In [0]:
def gradient_descent_step(x, cost, grad=None, step_size="backtracking"):
  if(grad == "random"):
    grad2 = np.array(make_rand_vector(len(x)))
  elif (hasattr(grad, '__call__')):
    grad2 = np.array(grad(x))
  else:
    grad2 = np.array((cost(x+0.001)-cost(x-0.001))/0.002)
  if(( isinstance(step_size, int)) or (isinstance(step_size, float))):
    step=step_size
  elif(step_size=="backtracking"):
    step=1
    while( (cost(x)-cost(x-step*grad2)) < ((step*np.linalg.norm(grad2)**2)/3) ):
      step = step*0.3
  elif(step_size == "line_search"):
    line = [-1, 1]
    while((line[1]- line[0])>1.1):
      if(f(np.array(line[0]))<f(np.array(line[1]))):
        line[1] = line[1]/constants.golden
#         this wrong
      else:
        line[0] = line[0]/constants.golden
#       as dis
    step = ((line[1]-line[0])/2)
  print(x, grad2, step)
  return (x - (grad2)*step)

In [0]:
def gradient_descent(initial_x, cost, num_steps, grad=None, step_size="backtracking"):
# Your code goes here
  x = initial_x
  trace = []
  trace.append(x)
  for i in range(num_steps):
    prev_x = x
    x = gradient_descent_step(prev_x, cost, grad, step_size)
    trace.append(x)
  return x, trace

In [115]:
cost = lambda x: np.sum(x**2)
grad = lambda x: 2*x
x = np.array([1,1, 3, 2, 1])
steps = "backtracking"
gradient_descent(initial_x=x,cost=f, num_steps = 10, grad=grad, step_size = 0.1)
# x1 = gradient_descent_step(x, cost, grad, step_size)
# gradient_descent_step(x1, cost, grad, step_size)

[1 1 3 2 1] [2 2 6 4 2] 0.1
[0.8 0.8 2.4 1.6 0.8] [1.6 1.6 4.8 3.2 1.6] 0.1
[0.64 0.64 1.92 1.28 0.64] [1.28 1.28 3.84 2.56 1.28] 0.1
[0.512 0.512 1.536 1.024 0.512] [1.024 1.024 3.072 2.048 1.024] 0.1
[0.4096 0.4096 1.2288 0.8192 0.4096] [0.8192 0.8192 2.4576 1.6384 0.8192] 0.1
[0.32768 0.32768 0.98304 0.65536 0.32768] [0.65536 0.65536 1.96608 1.31072 0.65536] 0.1
[0.262144 0.262144 0.786432 0.524288 0.262144] [0.524288 0.524288 1.572864 1.048576 0.524288] 0.1
[0.2097152 0.2097152 0.6291456 0.4194304 0.2097152] [0.4194304 0.4194304 1.2582912 0.8388608 0.4194304] 0.1
[0.16777216 0.16777216 0.50331648 0.33554432 0.16777216] [0.33554432 0.33554432 1.00663296 0.67108864 0.33554432] 0.1
[0.13421773 0.13421773 0.40265318 0.26843546 0.13421773] [0.26843546 0.26843546 0.80530637 0.53687091 0.26843546] 0.1


(array([0.10737418, 0.10737418, 0.32212255, 0.21474836, 0.10737418]),
 [array([1, 1, 3, 2, 1]),
  array([0.8, 0.8, 2.4, 1.6, 0.8]),
  array([0.64, 0.64, 1.92, 1.28, 0.64]),
  array([0.512, 0.512, 1.536, 1.024, 0.512]),
  array([0.4096, 0.4096, 1.2288, 0.8192, 0.4096]),
  array([0.32768, 0.32768, 0.98304, 0.65536, 0.32768]),
  array([0.262144, 0.262144, 0.786432, 0.524288, 0.262144]),
  array([0.2097152, 0.2097152, 0.6291456, 0.4194304, 0.2097152]),
  array([0.16777216, 0.16777216, 0.50331648, 0.33554432, 0.16777216]),
  array([0.13421773, 0.13421773, 0.40265318, 0.26843546, 0.13421773]),
  array([0.10737418, 0.10737418, 0.32212255, 0.21474836, 0.10737418])])