<a href="https://colab.research.google.com/github/Saadkhan55/Arm-Intern-Challenge/blob/master/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from random import gauss
from scipy import constants
%matplotlib inline

In [0]:
# Generates a random univt vector using gauss
# then divides by magnitude to make it unit
def rand_vector(length):
    unit_vector = [gauss(0, 1) for i in range(length)]
    size = sum(x**2 for x in unit_vector) ** 0.5
    return [x/size for x in unit_vector]
    
def grad_approx(cost, x):
  grad = x.copy()
  for i in range(len(x)):
    xi1 = x.copy()
    xi2 = x.copy()
    xi1[i] = xi1[i] + 0.01
    xi2[i] = xi2[i] - 0.01
    grad[i] = ((cost(xi1) - cost(xi2))/0.02)
  return grad

In [0]:
def gradient_descent_step(x, cost, grad=None, step_size="backtracking"):
  if(grad == "random"):
    grad2 = np.array(rand_vector(len(x)))
  elif (hasattr(grad, '__call__')):
    grad2 = np.array(grad(x))
  else:
    grad2 = grad_approx(cost, x)
  if(( isinstance(step_size, int)) or (isinstance(step_size, float))):
    step=step_size
  elif(step_size=="backtracking"):
    step=1
    while( (cost(x)-cost(x-step*grad2)) < ((step*np.linalg.norm(grad2)**2)/3) ):
      step = step*0.3
  elif(step_size == "line_search"):
    line = [-1, 1]
    while((line[1]- line[0])>1.1):
      if(f(np.array(line[0]))<f(np.array(line[1]))):
        line[1] = line[1]/constants.golden
#         this wrong
      else:
        line[0] = line[0]/constants.golden
#       as dis
    step = ((line[1]-line[0])/2)
  return (x - (grad2)*step)

In [0]:
def gradient_descent(initial_x, cost, num_steps, grad=None, step_size="backtracking"):
# Your code goes here
  x = initial_x
  trace = []
  trace.append(x)
  for i in range(1, num_steps):
    x = gradient_descent_step(trace[i-1], cost, grad, step_size)
    trace.append(x)
  return x, trace

In [194]:
cost = lambda x: np.sum(x**2)
grad = lambda x: 2*x
x = np.array([12,11, 32, 21, 16])
steps = "backtracking"
gradient_descent(initial_x=x,cost=f, grad = "randomjnij", num_steps = 50,  step_size = 0.1)

[1150 1050 3150 2050 1550]
[-206. -188. -566. -368. -278.]
[-164.8 -150.4 -452.8 -294.4 -222.4]
[-131.84 -120.32 -362.24 -235.52 -177.92]
[-105.472  -96.256 -289.792 -188.416 -142.336]
[ -84.3776  -77.0048 -231.8336 -150.7328 -113.8688]
[ -67.50208  -61.60384 -185.46688 -120.58624  -91.09504]
[ -54.001664  -49.283072 -148.373504  -96.468992  -72.876032]
[ -43.2013312  -39.4264576 -118.6988032  -77.1751936  -58.3008256]
[-34.56106496 -31.54116608 -94.95904256 -61.74015488 -46.64066048]
[-27.64885197 -25.23293286 -75.96723405 -49.3921239  -37.31252838]
[-22.11908157 -20.18634629 -60.77378724 -39.51369912 -29.85002271]
[-17.69526526 -16.14907703 -48.61902979 -31.6109593  -23.88001817]
[-14.15621221 -12.91926163 -38.89522383 -25.28876744 -19.10401453]
[-11.32496977 -10.3354093  -31.11617907 -20.23101395 -15.28321163]
[ -9.05997581  -8.26832744 -24.89294325 -16.18481116 -12.2265693 ]
[ -7.24798065  -6.61466195 -19.9143546  -12.94784893  -9.78125544]
[ -5.79838452  -5.29172956 -15.93148368 -

(array([-0.00229698, -0.00209627, -0.00631111, -0.00410334, -0.0030998 ]),
 [array([12, 11, 32, 21, 16]),
  array([-103.,  -94., -283., -184., -139.]),
  array([ -82.4,  -75.2, -226.4, -147.2, -111.2]),
  array([ -65.92,  -60.16, -181.12, -117.76,  -88.96]),
  array([ -52.736,  -48.128, -144.896,  -94.208,  -71.168]),
  array([ -42.1888,  -38.5024, -115.9168,  -75.3664,  -56.9344]),
  array([-33.75104, -30.80192, -92.73344, -60.29312, -45.54752]),
  array([-27.000832, -24.641536, -74.186752, -48.234496, -36.438016]),
  array([-21.6006656, -19.7132288, -59.3494016, -38.5875968, -29.1504128]),
  array([-17.28053248, -15.77058304, -47.47952128, -30.87007744,
         -23.32033024]),
  array([-13.82442598, -12.61646643, -37.98361702, -24.69606195,
         -18.65626419]),
  array([-11.05954079, -10.09317315, -30.38689362, -19.75684956,
         -14.92501135]),
  array([ -8.84763263,  -8.07453852, -24.3095149 , -15.80547965,
         -11.94000908]),
  array([ -7.0781061 ,  -6.45963081, -19.