<a href="https://colab.research.google.com/github/Saadkhan55/Arm-Intern-Challenge/blob/master/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from random import gauss
from scipy import constants
%matplotlib inline

In [0]:
def make_rand_vector(dims):
    vec = [gauss(0, 1) for i in range(dims)]
    mag = sum(x**2 for x in vec) ** .5
    return [x/mag for x in vec]
def grad_approx(cost, x):
  grad=[]
  for i in range(len(x)):
    xi = x[i]
    

In [0]:
def gradient_descent_step(x, cost, grad=None, step_size="backtracking"):
  if(grad == "random"):
    grad2 = np.array(make_rand_vector(len(x)))
  elif (hasattr(grad, '__call__')):
    grad2 = np.array(grad(x))
  else:
    grad2 = np.array((cost(x+0.001)-cost(x-0.001))/0.002)
  if(( isinstance(step_size, int)) or (isinstance(step_size, float))):
    step=step_size
  elif(step_size=="backtracking"):
    step=1
    while( (cost(x)-cost(x-step*grad2)) < ((step*np.linalg.norm(grad2)**2)/3) ):
      step = step*0.3
  elif(step_size == "line_search"):
    line = [-1, 1]
    while((line[1]- line[0])>1.1):
      if(f(np.array(line[0]))<f(np.array(line[1]))):
        line[1] = line[1]/constants.golden
#         this wrong
      else:
        line[0] = line[0]/constants.golden
#       as dis
    step = ((line[1]-line[0])/2)
#   print(x, grad2, step)
  return (x - (grad2)*step)

In [0]:
def gradient_descent(initial_x, cost, num_steps, grad=None, step_size="backtracking"):
# Your code goes here
  x = initial_x
  trace = []
  trace.append(x)
  for i in range(num_steps):
    prev_x = x
    x = gradient_descent_step(prev_x, cost, grad, step_size)
    trace.append(x)
  return x, trace

In [142]:
cost = lambda x: np.sum(x**2)
grad = lambda x: 2*x
x = np.array([1,1, 3, 2, 1])
steps = "backtracking"
gradient_descent(initial_x=x,cost=f, num_steps = 10,  step_size = 0.1)

16.016005
15.984005000000002
3.2000050000000004
3.2000049999999995
3.200005
3.2000049999999995
3.200005
3.2000049999999995
3.200005
3.2000050000000004
3.200005
3.2000049999999995
3.200005
3.2000050000000004
3.200005
3.2000049999999995
3.200005
3.2000050000000004
3.200005
3.2000049999999995


(array([-0.6, -0.6,  1.4,  0.4, -0.6]),
 [array([1, 1, 3, 2, 1]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6]),
  array([-0.6, -0.6,  1.4,  0.4, -0.6])])